services:

  backend-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    env_file:
      - .env
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:14.6-alpine
    env_file:
      - .env
