services:

  backend-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    env_file:
      - .env
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:14.6-alpine
    env_file:
      - .env

  redis:
    image: redis:7.0.5-alpine
    hostname: redis

  worker:
    build: 
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./backend:/backend
    links:
      - redis
    depends_on:
      - redis

  flower:
    build: 
      context: .
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - ./backend:/backend
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"