# Generated by Django 3.2.16 on 2024-03-06 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('services', '0004_auto_20240306_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='clients.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='services.plan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='services.service'),
            preserve_default=False,
        ),
    ]
