# Generated by Django 3.2.16 on 2024-03-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20240306_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='comment',
            field=models.CharField(db_index=True, default='default', max_length=50),
        ),
    ]
