# Generated by Django 3.2.16 on 2024-03-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_subscription_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='comment_a',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='subscription',
            name='comment_b',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
